First iteration of acdcsimulator
manucarrace/acdcSimulator pull request #1
Opened 2018-02-07 18:15 UTC by manucarrace

Let's try it!!!

2018-02-07 18:33 UTC, mrutid requested changes

2018-02-07 18:33 UTC, mrutid commented on lib/buildResponses.js
> +function createGCResponseMessage(request, response, callback) {
callback is never used. Remove

2018-02-07 18:33 UTC, mrutid commented on lib/buildResponses.js
> +function createContextBrokerNotification(request, response, callback) {
callback is never used. Remove.

2018-02-07 18:33 UTC, mrutid commented on lib/server.js
> +var app = express();
Style :) do the same than above.

2018-02-07 18:33 UTC, mrutid commented on lib/server.js
> +app.post('/sms/v2/smsoutbound', function(request, response){
Try to avoid anonymous functions.

Better define first function smsHandler() {}, and app.post('/sms/v2/smsoutbound', smsHandler) later

2018-02-07 18:33 UTC, mrutid commented on lib/server.js
> +       response.send('Error, message not valid')
Add a status code for error.

2018-02-07 18:33 UTC, mrutid commented on lib/server.js
> +app.listen(3000);
magic number, put on config.

2018-02-07 18:58 UTC, mrutid commented on config.js
> +module.exports = config;
Think about use Buffers in order to be able to play with encodings, bytearrays, hex...
https://nodejs.org/docs/latest-v4.x/api/buffer.html

(casi seguro que no hace falta... y son un buen lío, pero para los parseos y para montar mensajes intuyo que van a venir bien... asi que... pégate un poco)

2018-02-07 19:01 UTC, mrutid commented on lib/server.js
> +       response.send('Error, message not valid')
Semicolons please!! Javascript interpreter can infer them,... but it's a risky practice you pythoner!

2018-02-15 17:17 UTC, manucarrace commented on lib/buildResponses.js
> +            callback(response);
No me empapo de como tengo que invocar a la función de callback. No tengo claro que la necesite ...

2018-02-15 18:35 UTC, mrutid reviewed
Esta no te la paso ;) 

Lo hablamos!

2018-02-15 18:35 UTC, mrutid commented on config.js
> +var config = {};
why not module.exports = {..... }

2018-02-15 18:35 UTC, mrutid commented on constants.js
> +
this is more compact than config.js (choose the same style for both)

2018-02-15 18:35 UTC, mrutid commented on lib/buildResponses.js
> +
Use logger context.

var context = { campoparaambitoquenomeacuerdocomosellama : 'buildResponse'  }

logger.info(context, 'blablabla...);

2018-02-15 18:35 UTC, mrutid commented on lib/buildResponses.js
> +            if (response.statusCode = constant.HTTP_RESPONSE_OK) {
do you know what are you doing here? ;) = "asigment"  == "comparation"

It's always "true"

2018-02-15 18:35 UTC, mrutid commented on lib/buildResponses.js
> +    var request;
In general requires go better on top of global scope, single line. You can use them as global objects (so request param at invokeDashboard(request, options); is not necessary). (FORGET ABOUT IT. We will do a bigger refactor... continue).

2018-02-15 18:35 UTC, mrutid commented on lib/buildResponses.js
> +    var RPMessage = constant.CONTROL_CODE + constant.RP_MESSAGE + config.tank.sapCode + constant.RP_TEMPLATE;
declarations always on top of scope (in this case function scope)

2018-02-15 18:35 UTC, mrutid commented on lib/buildResponses.js
> +    var options = setHttpOptions(RPMessage);
same. Declare always on top of scope.

2018-02-15 18:35 UTC, mrutid commented on lib/smsHandler.js
> +    if (receivedMessage = constant.GC_MESSAGE) {
asignment!

2018-02-15 18:35 UTC, mrutid commented on lib/smsHandler.js
> +        responses.createContextBrokerNotification();
so... it's called responses, it will make a creation... but in fact it's going to send a request... ¿aposta?

2018-02-15 18:35 UTC, mrutid commented on lib/smsHandler.js
> +    if (receivedMessage = constant.GC_MESSAGE) {
try a switch/case

2018-02-15 18:35 UTC, mrutid commented on lib/smsHandler.js
> +        res.status(constant.HTTP_RESPONSE_OK).send('OK');
4 times same sentence. Sure you can make it with one ;)

2018-02-15 18:35 UTC, mrutid commented on lib/smsHandler.js
> +        responses.createContextBrokerNotification();
It smells like a refactor here and in buildResponses. What if we just build the payloads at buildResponses, and we make the request here (with invokeDashboard(responseString), Option object doesn't seem necessary as a param).

2018-02-15 19:30 UTC, mrutid commented on lib/smsHandler.js
> +    var receivedMessage = req.body.message.substring(4, 6);
too many point without error check

2018-02-16 08:29 UTC, AlvaroVega commented on lib/buildResponses.js
> +    invokeDashboard(request, options);
invocation to configEntry should be something like:
```
{"to":"tel:+34659167741","id":"90b12a80-c6ad-460f-a8c7-27f94c33564e","message":"ABCDRC50035212+34638444191N00000202030C3F3F3F00330000280237055A02FE000000000000000000000000000000000000000000000000000000000A010000FE000000FE6400","from":"tel:+34660218750"}
``
So RCMessage should be into that body. Shouldn't be?

2018-02-16 09:23 UTC, closed without merging